# Generated by Django 3.2.20 on 2023-07-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
