# Generated by Django 3.2.20 on 2023-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
